import { Metadata } from "next";
import RulesClient from "./RulesClient";

export const metadata: Metadata = {
  title: "Rules & Guidelines | CARAVAN '26",
  description: "General Rules and Guidelines for the CARAVAN '26 Inter-University Youth Festival.",
};

const GENERAL_RULES = [
  { title: "1. Eligibility", content: ["The competition is open to students currently enrolled in a recognized university, college or institution.", "Every participant must carry a valid College/University Identity Card.", "The Host University reserves the right to verify participant eligibility at any stage."] },
  { title: "2. Registration", content: ["All participants must register within the prescribed deadline.", "Incomplete or incorrect registrations may be rejected.", "Any change in participant or team details after registration will be subject to approval by the Organizing Committee.", "Registration shall be considered complete only after fulfilment of all requirements communicated by the organizers."] },
  { title: "3. Institutional Representation", content: ["Participants shall officially represent their respective college/university/institution.", "Where required, participation must be verified by the concerned HOD, faculty coordinator or institutional representative.", "One participant may take part in more than one competition only if the event timings do not clash."] },
  { title: "4. Reporting Time", content: ["Participants must report at the designated venue at least 30 minutes before the scheduled starting time.", "Late entry may not be permitted once the competition has started.", "Participants must complete the required reporting/verification formalities before entering the competition venue."] },
  { title: "5. Event Schedule", content: ["Participants are responsible for checking the final schedule, venue and reporting time of their respective events.", "The Host University reserves the right to change the schedule, venue or sequence of events due to administrative or unavoidable circumstances.", "Official updates will be communicated through authorized channels."] },
  { title: "6. Event-Specific Rules", content: ["Every competition will have separate rules regarding team size, theme, duration, materials, performance time, submission requirements and judging criteria.", "Participants must follow both the General Rules and the Event-Specific Rules.", "Event-specific instructions issued by the concerned Event Coordinator must be followed."] },
  { title: "7. Materials and Equipment", content: ["Participants must bring their own materials, costumes, instruments, stationery, devices and other required equipment unless specifically mentioned otherwise.", "The Host University will provide only those facilities or materials specifically mentioned in the event guidelines.", "Participants shall remain responsible for their personal belongings and equipment."] },
  { title: "8. Originality and Fair Practice", content: ["Entries must be original wherever originality is a requirement of the competition.", "Plagiarism, impersonation, copying, unauthorized assistance or any form of unfair practice may result in disqualification.", "Participants may be asked to provide an originality declaration for artwork, writing, photography, media or design entries."] },
  { title: "9. Use of AI and Digital Tools", content: ["Use of AI-generated content, digital editing, external software or other technological assistance will depend upon the rules of the individual competition.", "Where AI-generated material is prohibited, its use may lead to disqualification.", "Participants may be required to disclose the use of AI or digital assistance wherever applicable."] },
  { title: "10. Code of Conduct", content: ["Participants must maintain discipline, dignity and respectful behaviour throughout the event.", "Misconduct, abusive behaviour, harassment, disruption of an event or damage to university property may lead to disqualification and removal from the premises.", "Instructions issued by university authorities, organizing committees, volunteers and security personnel must be followed."] },
  { title: "11. Prohibited Items", content: ["Alcohol, narcotic substances, weapons, inflammable substances and any item prohibited under university regulations or applicable law are strictly prohibited.", "Potentially hazardous materials required for a particular event may only be used with prior permission from the organizers."] },
  { title: "12. Judging", content: ["Competitions will be evaluated by judges appointed by the Host University.", "Judging will be based on the criteria mentioned in the respective event rules.", "The decision of the judges shall be final and binding.", "Participants shall not directly approach or argue with judges regarding marks, rankings or results."] },
  { title: "13. Disqualification", content: ["Participants may be disqualified for violation of rules, misconduct, plagiarism, use of prohibited materials, exceeding prescribed time limits, providing false information or interfering with another participant or team."] },
  { title: "14. Tie-Breaking", content: ["In case of a tie, the jury may use additional judging criteria or conduct an additional round wherever necessary.", "The jury's decision in such cases shall be final."] },
  { title: "15. Results and Awards", content: ["Results will be announced through the official channels of the Host University.", "Winners may be required to remain present for the prize distribution or valedictory ceremony.", "Prizes, certificates, trophies or medals will be awarded according to the announced structure of each competition."] },
  { title: "16. Certificates", content: ["Participation certificates will be issued only to participants who have successfully registered and participated in the concerned event.", "Participants must ensure that their name, institution and other details submitted during registration are correct."] },
  { title: "17. Photography and Media Coverage", content: ["Events may be photographed, filmed or recorded by the Host University for documentation, publicity, social media, press and institutional purposes.", "Participants should inform the organizers in advance if any specific restriction regarding photography or recording applies."] },
  { title: "18. Intellectual Property", content: ["Ownership of original creative work will ordinarily remain with the participant.", "The Host University may use photographs or recordings of participating works and performances for academic, archival, promotional and institutional purposes."] },
  { title: "19. Travel, Accommodation and Food", content: ["Travel expenses shall be borne entirely by the participants or their respective institutions.", "Accommodation will not be provided by the Host University unless specifically communicated separately.", "Food, meals and refreshments are not included in the registration/participation and will not be provided by the Host University unless specifically announced."] },
  { title: "20. Personal Belongings", content: ["Participants shall remain responsible for their personal belongings, valuables, instruments and equipment.", "The Host University will not be responsible for any loss, theft or damage."] },
  { title: "21. Faculty/Team Coordinator", content: ["Participating institutions may nominate a faculty or team coordinator.", "The coordinator will act as the official point of communication between the institution and the Host University.", "The coordinator shall ensure that participants follow the schedule and competition rules."] },
  { title: "22. Grievances", content: ["Any genuine grievance must be reported to the concerned Event Coordinator or designated committee.", "Arguments with judges, volunteers or organizers will not be entertained.", "The decision of the authorized committee shall be final."] },
  { title: "23. Cancellation or Modification", content: ["The Host University reserves the right to modify, postpone, merge or cancel any competition due to insufficient participation, administrative reasons, safety concerns or circumstances beyond its control."] },
  { title: "24. Host University Authority", content: ["The Organizing Committee reserves the right to interpret the rules and take appropriate decisions in situations not specifically covered in this rulebook.", "All participants and participating institutions shall abide by the rules and regulations of the Host University."] },
];

export default function RulesPage() {
  return <RulesClient rules={GENERAL_RULES} />;
}
